on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm ci
    - run: sudo apt-get install xvfb
    - name: ESLint
      run: npm run lint
    - name: Jest
      run: xvfb-run --auto-servernum npm run jest
